name = "L2Metrics"
uuid = "4921383a-abe2-4720-be29-9ff650b2e707"
authors = ["Sasha Petrenko <sap625@umsystem.edu> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PrecompileSignatures = "91cefc8d-f054-46dc-8f8c-26e11d7c5411"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
julia = "1"
JSON = "0.24"
PythonCall = "0.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
